//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUELLASCLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HUELLASCLIENTE()
        {
            this.REGISTROS = new HashSet<REGISTRO>();
        }
    
        public long ID { get; set; }
        public byte[] HUELLA { get; set; }
        public Nullable<long> QUALITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO> REGISTROS { get; set; }
    }
}
