//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis_Gym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtlantisHuellasEntities : DbContext
    {
        public AtlantisHuellasEntities()
            : base("name=AtlantisHuellasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HUELLASCLIENTE> HUELLASCLIENTES { get; set; }
        public virtual DbSet<REGISTRO> REGISTROS { get; set; }
    }
}
